model:
  img_channels : 1
  img_size : 32
  down_channels : [32, 64, 128, 256]
  mid_channels : [256, 256, 128]
  down_sample : [True, True, False]
  time_emb_dim : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2
  num_heads : 4

dataset:
  save_path: 'data/'
  img_ext: '.png'

diffusion:
  algo: 'linear'
  n_steps: 1000
  beta_start: 0.001
  beta_end: 0.02

train:
  batch_size: 64
  num_epochs: 40
  lr: 0.0001
  checkpoint_folder: 'checkpoints'
  checkpoint_name: '40_epochs.pth'

sample:
  n_samples: 100
