model:
  img_channels : 1
  img_size : 32
  down_channels : [16, 32, 64]
  mid_channels : [64, 64, 32]
  down_sample : [True, False]
  time_emb_dim : 64
  num_down_layers : 1
  num_mid_layers : 1
  num_up_layers : 1
  num_heads : 2

dataset:
  save_path: 'data/'
  img_ext: '.png'

diffusion:
  algo: 'linear'
  n_steps: 1000
  beta_start: 0.001
  beta_end: 0.02

train:
  batch_size: 64
  num_epochs: 1
  lr: 0.0001
  checkpoint_folder: 'checkpoints'
  checkpoint_name: '4_epochs.pth'
