model:
  img_channels : 1
  img_size : 32
  down_channels : [64, 128, 256, 512]
  mid_channels : [512, 512, 256]
  down_sample : [True, True, False]
  time_emb_dim : 256
  num_down_layers : 3
  num_mid_layers : 3
  num_up_layers : 3
  num_heads : 8

dataset:
  save_path: 'data/'
  img_ext: '.png'

diffusion:
  algo: 'linear'
  n_steps: 1000
  beta_start: 0.001
  beta_end: 0.02

train:
  batch_size: 64
  num_epochs: 10
  lr: 0.0002
  checkpoint_folder: 'checkpoints'
  checkpoint_name: '10_big_epochs.pth'

sample:
  n_samples: 100
